version: '3'

services:

  redmine:
    image: redmine
    container_name: redmine
    restart: always
    depends_on:
      - redmine-db
    ports:
      - 8080:3000
    environment: 
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: 123456
    volumes:
      - redmine-data:/usr/src/redmine/files

  redmine-db:
    image: mariadb
    container_name: redmine-db
    restart: always
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
     ]
    environment:
      MYSQL_ROOT_PASSWORD: 123!@#
      MYSQL_USER: redmine
      MYSQL_PASSWORD: 123456    
      MYSQL_DATABASE: redmine
    volumes:
      - redmine-db-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
     - redmine-db
     - gitea-db
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=gitea-db,redmine-db
      
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea-data:/data
    ports:
      - "8088:3000"
      - "10022:22"
    depends_on:
      - gitea-db

  gitea-db:
    image: mariadb
    container_name: gitea-db
    restart: always
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
     ]
    environment:
      MYSQL_ROOT_PASSWORD: 123!@#
      MYSQL_USER: gitea
      MYSQL_PASSWORD: 123456    
      MYSQL_DATABASE: gitea
    volumes:
      - gitea-db-data:/var/lib/mysql

volumes:
  redmine-data:
  redmine-db-data:
  gitea-db-data:
  gitea-data: